### ISSUE TITLE
plugin download broken?

### ISSUE THREAD

**Issue by Nerxxy** [esnar11/SkipReplay#1]
not sure if this is a problem with the plugin or bakkes website but when i try to install this plugin with bakkesmod it doesnt actually download/install, ive tried using the plugin manager but still doesnt want to download or install

**Comment by Nerxxy** [comment]
i have to click the drop down menu and click "download files" to get them but doing that as you know i wont get automatic updates

**Comment by esnar11** [comment]
Hey Nerxxy,

Thanks for letting me know.
The plugin was uploaded to the site wrongly by the admins. They will fix it in the next update.

**Comment by luukvbaal** [comment]
FYI anyone who has downloaded the plugin since the latest update should clean their bakkesmod folder as they will have the `SkipReplay.dll` and `settings` folder in their bakkesmod root.

**Comment by Nerxxy** [comment]
@esnar11 is the plugin going to be updated soon? not sure if it has been updated since you replied but it still doesnt download from the site.

@luukvbaal by root folder you mean the one thats in "appdate - roaming - bakkesmod - bakkesmod"? or the old location? "steam - steam apps - common - rocket league - ETC"?

**Comment by luukvbaal** [comment]
For me it was in `%APPDATA%/bakkesmod/bakkesmod/`. You can delete the `SkipReplay.dll` and `settings` folder there.

**Comment by Nerxxy** [comment]
i dont see why i need to delete it tho, it still works just doesnt download with plugin manager thats all

**Comment by luukvbaal** [comment]
The point is that it does download with plugin manager but it installs the files in the incorrect location. Until it is re-approved and reuploaded by the bakkesmod team, the current install from the website places the files in `%APPDATA%/bakkesmod/bakkesmod/` instead of  `%APPDATA%/bakkesmod/bakkesmod/plugins`.

The files and folder `%APPDATA%/bakkesmod/bakkesmod/{SkipReplay.dll,plugins}` can safely be deleted. This won't affect the working plugin if you had installed it to the correct location manually.

**Comment by Nerxxy** [comment]
ohhhhhh ok now i understand i didnt even notice it actually downloaded, thanks :)

**Comment by esnar11** [comment]
Closing since the plugin has been updated on the website.
